version: "3.7"
services:
  ldap:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      PORT: 389
      LOGLEVEL: debug
      DB_HOST: db
      DB_USERNAME: tailor
      DB_PASSWORD: tailor
      DB_NAME: tailor
      DB_PORT: "0"
      USERNAME: cn=admin,dc=tailor
      PASSWORD: password
    ports:
      - "8389:389"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
      - ./db/logs:/var/log
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: tailor
      POSTGRES_PASSWORD: tailor
      POSTGRES_DB: tailor
    ports:
      - "65432:5432"